Edit deploy-staging.yml

diff --git a/.github/workflows/deploy-staging.yml b/.github/workflows/deploy-staging.yml
--- a/.github/workflows/deploy-staging.yml
+++ b/.github/workflows/deploy-staging.yml
@@ -47,18 +47,19 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
           script: |
             APP_STG_PATH="/home/ubuntu/staging"
-            if [ ! -d "$APP_STG_PATH" ]; then
+            REPO_PATH="/home/ubuntu/music-streaming"
+            if [ ! -d "$REPO_PATH" ]; then
               ssh-keyscan github.com >> ~/.ssh/known_hosts
-              git clone git@github.com:dwididit/music-streaming.git $APP_STG_PATH
+              git clone git@github.com:dwididit/music-streaming.git $REPO_PATH
             else
-              cd $APP_STG_PATH
-              sudo docker-compose -f ../docker-compose.yaml down --remove-orphans --timeout 60 pacmusic-stg || true
+              cd $REPO_PATH
+              sudo docker-compose down --remove-orphans --timeout 60 pacmusic-stg || true
               git pull origin main
             fi
-            cd $APP_STG_PATH
+            cd $REPO_PATH
 
-            if [ ! -f "../docker-compose.yaml" ]; then
-              echo "Error: ../docker-compose.yaml not found in $(pwd)"
+            if [ ! -f "docker-compose.yaml" ]; then
+              echo "Error: docker-compose.yaml not found in $(pwd)"
               exit 1
             fi
 
@@ -83,10 +84,10 @@ jobs:
             APP_PROD_PORT=5000
             EOT
 
-            sudo docker-compose -f ../docker-compose.yaml down --remove-orphans --timeout 60 pacmusic-stg || true
+            sudo docker-compose down --remove-orphans --timeout 60 pacmusic-stg || true
             git pull origin main
 
-            sudo docker-compose -f ../docker-compose.yaml up --build -d pacmusic-stg
+            sudo docker-compose up --build -d pacmusic-stg
 
       - name: Wait for the application to start
         run: sleep 10
